### ISSUE TITLE
Replace bdk FeeRate with rust-bitcoin FeeRate

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1136] opened 2023-09-29 00:21 UTC
**Describe the enhancement**  

We should be able to replace the bdk `FeeRate` struct with the `FeeRate` from rust-bitcoin since they serve the same purpose and it's less confusing to users to have only one version of the type. Any missing functions from the bdk::FeeRate should be upstreamed to rust-bitcoin or moved to a new bdk trait implemented on rust-bitcoin's `FeeRate`. 

**Use case**  

All existing uses for bdk's `FeeRate`.

**Additional context**

https://docs.rs/bitcoin/0.30.1/bitcoin/blockdata/fee_rate/struct.FeeRate.html
https://docs.rs/bdk/1.0.0-alpha.1/bdk/struct.FeeRate.html

**Comment by danielabrozzoni** [comment] 2023-09-29 11:19
This is a duplicate of https://github.com/bitcoindevkit/bdk/issues/1037, but since this is way better specified, I'm closing that one and leaving this open instead haha

**Comment by notmandatory** [comment] 2023-11-16 14:10
We have two PRs working on resolving this issue, #1141 and #1216. I've moved them all to alpha.4 release so everyone has time to review them and we need to decide which one to close.

**Comment by notmandatory** [comment] 2024-03-20 02:41
A small change but I think we should push to 2.0 milestone.

**Closed as completed** 2024-03-22 04:34 UTC
Labels: new feature, good first issue, module-wallet
