### ISSUE TITLE
TxOdering::Shuffle is not shuffling the inputs

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#865] opened 2023-02-14 05:30 UTC
TxOdering::Shuffle is not shuffling the inputs (only the outputs).

Bug found while doing bdk core integration. I think it's moderately serious so I think this fix should be backported.

**Comment by nassersaazi** [comment] 2023-02-28 13:44
i would love to work on this! it would be my first time contributing to the project, so some context around the issue is highly appreciated

**Comment by notmandatory** [comment] 2023-02-28 23:01
Hi @nassersaazi thanks! but I didn't see your note and I just created #876 . Please feel free to review that PR, but it's very simple, the only interesting thing is to see if you can think of any other test cases or any reason why the tx inputs shouldn't be shuffled when we shuffle the outputs.

**Comment by nassersaazi** [comment] 2023-02-28 23:19
thanks @notmandatory .reviewing the PR will help me get familiar with the codebase and perhaps pick up another issue 😄

**Comment by notmandatory** [comment] 2024-03-17 23:27
Fixed by @LLFourn with 5985706c1a8c6358d840eb12ed678836b56ffb0

**Closed as completed** 2024-03-17 23:27 UTC
Labels: bug, module-wallet
